name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: mvn package
        env:
          _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
        run: |
          set -e
          ./mvnw -V package
      - name: cf push
        if: github.ref == 'refs/heads/master'
        env:
          CF_CLI_VERSION: 7.2.0
          CF_API: ${{ secrets.CF_API }}
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_ORG: ${{ secrets.CF_ORG }}
          CF_SPACE: ${{ secrets.CF_SPACE }}
        run: |
          set -e
          wget -q "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=${CF_CLI_VERSION}&source=github-rel" -O cf.tgz
          tar xzf cf.tgz
          rm -f LICENSE NOTICE cf.tgz
          ./cf7 login -a ${CF_API} -u ${CF_USERNAME} -p ${CF_PASSWORD} -o ${CF_ORG} -s ${CF_SPACE}
          ./cf7 push --strategy rolling
      - name: E2E test
        if: github.ref == 'refs/heads/master'
        env:
          TARGET_URL: ${{ secrets.TARGET_URL }}
        run: |
          set -ex
          TODO_ID=$(curl -v -s ${TARGET_URL}/todos -H "Content-Type: application/json" -d '{"todoTitle": "Demo"}' | jq -r .todoId)
          curl -v -s ${TARGET_URL}/todos
          curl -v -s ${TARGET_URL}/todos/${TODO_ID}
          curl -v -s -X PUT ${TARGET_URL}/todos/${TODO_ID} -H "Content-Type: application/json" -d '{"finished": "true"}'
          curl -v -s -X DELETE ${TARGET_URL}/todos/${TODO_ID}
          curl -v -s ${TARGET_URL}/todos